# Generated by Django 5.1.3 on 2024-11-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
                ('mae', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeCadastro', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('pessoa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('anoIngresso', models.IntegerField()),
                ('pessoa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaDeAtuacao', models.CharField(max_length=45)),
                ('numeroDeRegistro', models.IntegerField()),
                ('pessoa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas')),
            ],
        ),
    ]
